const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={build:'REBUILD 001',mode:'move',photo:null,outline:[],fittings:[],notches:[],holes:[],radii:[],measurements:{widths:[],heights:[],overallW:'',leftH:'',rightH:''},production:null,history:[]};
const stage=$('#stage'),img=$('#photo'),overlay=$('#overlay'),octx=overlay.getContext('2d'),dctx=$('#drawing').getContext('2d'),pctx=$('#production').getContext('2d');
function snapshot(){state.history.push(JSON.stringify({outline:state.outline,fittings:state.fittings,notches:state.notches,holes:state.holes,radii:state.radii,measurements:state.measurements,production:state.production}));if(state.history.length>30)state.history.shift()}
function restore(){const s=state.history.pop();if(!s)return;Object.assign(state,JSON.parse(s));renderAll();buildFields()}
function fitCanvas(){const r=stage.getBoundingClientRect();overlay.width=Math.max(1,Math.round(r.width*devicePixelRatio));overlay.height=Math.max(1,Math.round(r.height*devicePixelRatio));octx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}
function ptFromEvent(e){const r=overlay.getBoundingClientRect();const t=e.touches?.[0]||e;return{x:(t.clientX-r.left)/r.width,y:(t.clientY-r.top)/r.height}}
function denorm(p){const r=overlay.getBoundingClientRect();return{x:p.x*r.width,y:p.y*r.height}}
function near(p,arr,rad=.035){let best=-1,bd=1e9;arr.forEach((q,i)=>{const d=Math.hypot(p.x-q.x,p.y-q.y);if(d<bd&&d<rad){bd=d;best=i}});return best}
function renderOverlay(){fitCanvas();const r=overlay.getBoundingClientRect();octx.clearRect(0,0,r.width,r.height);if(state.outline.length){octx.strokeStyle='#39a9ff';octx.lineWidth=3;octx.beginPath();state.outline.forEach((p,i)=>{const q=denorm(p);i?octx.lineTo(q.x,q.y):octx.moveTo(q.x,q.y)});if(state.outline.length>2)octx.closePath();octx.stroke();state.outline.forEach(p=>{const q=denorm(p);octx.fillStyle='#39a9ff';octx.beginPath();octx.arc(q.x,q.y,6,0,Math.PI*2);octx.fill()})}state.fittings.forEach(f=>{const q=denorm(f);octx.strokeStyle='#ff514d';octx.lineWidth=3;octx.strokeRect(q.x-f.w*r.width/2,q.y-f.h*r.height/2,f.w*r.width,f.h*r.height);octx.fillStyle='#ff514d';octx.font='bold 12px sans-serif';octx.fillText(f.code,q.x+6,q.y-6)});state.notches.forEach(n=>{const q=denorm(n);octx.fillStyle='#ff9d2e';octx.beginPath();octx.arc(q.x,q.y,6,0,Math.PI*2);octx.fill()});state.holes.forEach(h=>{const q=denorm(h);octx.strokeStyle='#e5d85b';octx.beginPath();octx.arc(q.x,q.y,8,0,Math.PI*2);octx.stroke()})}
function sortedStations(){const xs=[...new Set(state.outline.map(p=>Math.round(p.x*10000)/10000))].sort((a,b)=>a-b);return xs.length>1?xs.slice(1):[]}
function buildFields(){const xs=sortedStations();const widthCount=Math.max(1,xs.length);const topRuns=[...new Set(state.outline.map(p=>Math.round(p.y*1000)/1000))];const heightCount=Math.max(2,topRuns.length);while(state.measurements.widths.length<widthCount)state.measurements.widths.push('');state.measurements.widths.length=widthCount;while(state.measurements.heights.length<heightCount)state.measurements.heights.push('');state.measurements.heights.length=heightCount;$('#widthFields').innerHTML=state.measurements.widths.map((v,i)=>`<label class="measure"><span>W${i+1}</span><input data-w="${i}" inputmode="decimal" value="${v??''}"></label>`).join('');$('#heightFields').innerHTML=state.measurements.heights.map((v,i)=>`<label class="measure"><span>H${i+1}</span><input data-h="${i}" inputmode="decimal" value="${v??''}"></label>`).join('');$$('[data-w]').forEach(el=>el.oninput=()=>{state.measurements.widths[+el.dataset.w]=el.value;draw()});$$('[data-h]').forEach(el=>el.oninput=()=>{state.measurements.heights[+el.dataset.h]=el.value;draw()});$$('#widthFields input,#heightFields input,#mOverallW,#leftH,#rightH').forEach((el,i,a)=>el.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();a[i+1]?.focus()}});$('#mOverallW').value=state.measurements.overallW||'';$('#leftH').value=state.measurements.leftH||'';$('#rightH').value=state.measurements.rightH||''}
function drawingGeometry(ctx,prod=false){const c=ctx.canvas,w=c.width,h=c.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#111';ctx.fillStyle='#111';ctx.lineWidth=4;if(state.outline.length<2){ctx.font='28px sans-serif';ctx.fillText('Load or scan a splashback to create the drawing.',50,70);return}const minX=Math.min(...state.outline.map(p=>p.x)),maxX=Math.max(...state.outline.map(p=>p.x)),minY=Math.min(...state.outline.map(p=>p.y)),maxY=Math.max(...state.outline.map(p=>p.y));const pad=150,scale=Math.min((w-2*pad)/(maxX-minX||1),(h-2*pad)/(maxY-minY||1));const cv=p=>({x:pad+(p.x-minX)*scale,y:pad+(p.y-minY)*scale});ctx.beginPath();state.outline.forEach((p,i)=>{const q=cv(p);i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y)});ctx.closePath();ctx.stroke();state.fittings.forEach(f=>{const q=cv(f),fw=f.w*scale,fh=f.h*scale;ctx.strokeRect(q.x-fw/2,q.y-fh/2,fw,fh);ctx.font='bold 20px sans-serif';ctx.fillText(f.code,q.x+8,q.y)});state.holes.forEach(x=>{const q=cv(x);ctx.beginPath();ctx.moveTo(q.x-10,q.y);ctx.lineTo(q.x+10,q.y);ctx.moveTo(q.x,q.y-10);ctx.lineTo(q.x,q.y+10);ctx.stroke()});ctx.font='22px sans-serif';const vals=prod&&state.production?state.production.widths:state.measurements.widths;vals.forEach((v,i)=>{if(v){ctx.fillText(`W${i+1}  ${v} mm`,70,80+i*30)}});const hs=prod&&state.production?state.production.heights:state.measurements.heights;hs.forEach((v,i)=>{if(v){ctx.fillText(`H${i+1}  ${v} mm`,w-250,80+i*30)}});const ow=prod&&state.production?state.production.overallW:state.measurements.overallW;if(ow)ctx.fillText(`OVERALL ${ow} mm`,w/2-100,h-65);ctx.font='bold 18px sans-serif';ctx.fillText(prod?'PRODUCTION DRAWING':'MEASURED VALUES',50,h-25)}
function draw(){drawingGeometry(dctx,false);drawingGeometry(pctx,true)}
function renderAll(){renderOverlay();draw()}
async function loadFile(file){if(!file)return;const url=URL.createObjectURL(file);img.onload=()=>{state.photo=url;$('#scanStatus').textContent=`Photo loaded · ${Math.round(file.size/1024)} KB`;renderOverlay()};img.src=url}
$('#photoInput').onchange=e=>loadFile(e.target.files[0]);$('#cameraInput').onchange=e=>loadFile(e.target.files[0]);
$('#scanBtn').onclick=async()=>{if(!img.src){$('#scanStatus').textContent='Load a photo first.';return}snapshot();$('#scanStatus').textContent='Scanning…';try{const canvas=document.createElement('canvas');const max=1600,s=Math.min(1,max/img.naturalWidth,max/img.naturalHeight);canvas.width=Math.round(img.naturalWidth*s);canvas.height=Math.round(img.naturalHeight*s);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);const imageDataUrl=canvas.toDataURL('image/jpeg',.82);const r=await fetch('/api/detect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({imageDataUrl})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Scan failed');state.outline=data.outline||[];state.fittings=data.fittings||[];state.notches=data.notches||[];$('#scanStatus').textContent=`Scan complete · ${state.outline.length} outline points · ${state.fittings.length} fittings`;buildFields();renderAll()}catch(err){$('#scanStatus').textContent=`Scan unavailable: ${err.message}. Manual editing remains available.`}}
let drag=null;overlay.addEventListener('pointerdown',e=>{const p=ptFromEvent(e);if(state.mode==='move'){const i=near(p,state.outline);if(i>=0){snapshot();drag={type:'outline',i};overlay.setPointerCapture(e.pointerId);return}const fi=near(p,state.fittings,.05);if(fi>=0){snapshot();drag={type:'fitting',i:fi};overlay.setPointerCapture(e.pointerId)}}else{snapshot();if(state.mode==='outline')state.outline.push(p);if(['single','double','cooker'].includes(state.mode)){const cfg={single:['S/S',75,75],double:['D/S',135,75],cooker:['C/S',75,135]}[state.mode];state.fittings.push({...p,code:cfg[0],w:cfg[1]/3000,h:cfg[2]/1000})}if(state.mode==='notch')state.notches.push(p);if(state.mode==='hole')state.holes.push(p);if(state.mode==='radius')state.radii.push({...p,r:20});if(state.mode==='erase'){const i=near(p,state.outline);if(i>=0)state.outline.splice(i,1);else{const fi=near(p,state.fittings,.05);if(fi>=0)state.fittings.splice(fi,1)}}buildFields();renderAll()}});overlay.addEventListener('pointermove',e=>{if(!drag)return;const p=ptFromEvent(e);if(drag.type==='outline')state.outline[drag.i]=p;else state.fittings[drag.i]={...state.fittings[drag.i],...p};renderAll()});overlay.addEventListener('pointerup',()=>{drag=null;buildFields();renderAll()});
$$('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;$$('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));$('#modeBadge').textContent=b.textContent});
$('#applyBtn').onclick=()=>{state.measurements.overallW=$('#mOverallW').value;state.measurements.leftH=$('#leftH').value;state.measurements.rightH=$('#rightH').value;draw()};
$('#productionBtn').onclick=()=>{const n=x=>Number(x)||0;let ow=n(state.measurements.overallW);const unit=$('#unitEdge').value;if(unit==='left'||unit==='right')ow-=2;if(unit==='both')ow-=4;if($('#revealAllowance').checked)ow+=7;if($('#overlapAllowance').checked)ow-=8;const widths=state.measurements.widths.map(v=>n(v));const heights=state.measurements.heights.map(v=>n(v));state.production={overallW:ow||'',widths,heights};$('#productionSummary').textContent=ow?`Production overall width: ${ow} mm`:'Enter measured overall width first.';draw()};
$('#undoBtn').onclick=restore;$('#resetBtn').onclick=()=>{if(confirm('Reset this job?')){location.reload()}};$('#printBtn').onclick=()=>window.print();
$('#saveBtn').onclick=()=>{localStorage.setItem('splashcad-rebuild-job',JSON.stringify({...state,history:[]}));$('#productionSummary').textContent='Job saved on this device.'};
$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify({...state,history:[]},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='splashcad-job.json';a.click()};
$('#voiceBtn').onclick=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){alert('Voice recognition is not available in this browser.');return}const fields=[...$$('#widthFields input'),$('#mOverallW'),...$$('#heightFields input'),$('#leftH'),$('#rightH')];let i=Math.max(0,fields.findIndex(x=>x===document.activeElement));const rec=new SR();rec.continuous=true;rec.interimResults=false;rec.lang='en-IE';$('#voiceBtn').textContent='🎤 Listening';rec.onresult=e=>{const text=e.results[e.results.length-1][0].transcript.toLowerCase();if(text.includes('stop')){rec.stop();return}if(text.includes('back'))i=Math.max(0,i-1);else if(text.includes('next'))i=Math.min(fields.length-1,i+1);else{const m=text.replace(/,/g,'').match(/\d+(?:\.\d+)?/);if(m){fields[i].value=m[0];fields[i].dispatchEvent(new Event('input'));i=Math.min(fields.length-1,i+1)}}fields[i]?.focus()};rec.onend=()=>{$('#voiceBtn').textContent='🎤 Voice entry'};rec.start()};
window.addEventListener('resize',renderOverlay);if('serviceWorker'in navigator)navigator.serviceWorker.register('/service-worker.js').catch(()=>{});buildFields();draw();