const CACHE='splashcad-6-0-22-u014-manual-edge-touch-20260816181500';
const CORE=['/','/index.html','/hob.html','/window.html','/styles.css','/splashcad-app.js','/window-wall.js','/voice.js','/tablet.js','/manifest.webmanifest','/splashcad-icon.svg'];
const TABLET_PATCH=`
;(()=>{
  const BUILD='ALPHA 6.0.22 · UPDATE 014';
  document.title='SplashCAD — '+BUILD;
  const proof=document.querySelector('.alpha-proof');if(proof)proof.textContent=BUILD;
  const brand=document.querySelector('.brand p');if(brand)brand.textContent=BUILD+' · Locked Detection + Dimension Engine V2';

  const style=document.createElement('style');
  style.textContent='body.tablet-field-mode .workspace-shell{grid-template-columns:155px minmax(0,1fr) 300px!important;gap:8px!important;height:calc(100vh - 64px)!important;overflow:hidden!important}body.tablet-field-mode .sidebar{display:block!important;grid-column:1!important;overflow:hidden!important}body.tablet-field-mode .sidebar>*:not(#tabletProcedurePanel){display:none!important}#tabletProcedurePanel{display:none}body.tablet-field-mode #tabletProcedurePanel{display:block!important;margin:0!important;position:sticky;top:0;padding:10px!important}#tabletProcedurePanel h2{margin:0 0 9px;font-size:13px;color:#d1fae5}#tabletProcedurePanel .procedure-step{padding:8px 0;border-top:1px solid #263a34;font-size:11px;line-height:1.3;color:#cbd5e1}#tabletProcedurePanel .procedure-step strong{display:block;color:#6ee7b7;font-size:12px;margin-bottom:2px}body.tablet-field-mode .main-workspace{grid-column:2!important;height:100%!important;min-height:0!important;overflow-y:auto!important;overflow-x:hidden!important;overscroll-behavior-y:contain!important;-webkit-overflow-scrolling:touch;padding-bottom:120px!important}body.tablet-field-mode .rightbar{grid-column:3!important;height:100%!important;max-height:none!important;min-height:0!important;overflow-y:auto!important;overscroll-behavior-y:contain!important;-webkit-overflow-scrolling:touch;padding-bottom:120px!important}body.tablet-field-mode #photoStage,body.tablet-field-mode #photoOverlay,body.tablet-field-mode #wallPhoto{touch-action:none!important}body.tablet-field-mode .photo-stage,body.tablet-field-mode #wallPhoto{min-height:68vh!important;max-height:82vh!important}.edge-manual-controls{margin:8px 0;padding:9px;border:1px solid #245343;border-radius:10px;background:#0b1915}.edge-manual-tools{display:flex;gap:6px;flex-wrap:wrap}.edge-manual-tools button.active{background:#17d99a;color:#04120e}.edge-manual-status{font-size:11px;color:#a7f3d0;margin-top:7px;line-height:1.35}.edge-manual-overlay{position:absolute;inset:0;width:100%;height:100%;z-index:12;touch-action:none}';
  document.head.appendChild(style);

  const sidebar=document.querySelector('.sidebar');
  if(sidebar&&!document.getElementById('tabletProcedurePanel')){
    const p=document.createElement('section');p.id='tabletProcedurePanel';p.className='panel';
    p.innerHTML='<h2>Procedure</h2><div class="procedure-step"><strong>1 · Photo</strong>Take a photo or choose one.</div><div class="procedure-step"><strong>2 · Scan</strong>Scan outline + sockets.</div><div class="procedure-step"><strong>3 · Edit</strong>Correct outline, sockets, notches and shapes.</div><div class="procedure-step"><strong>4 · Measure</strong>Widths first, then heights.</div>';
    sidebar.prepend(p);
  }

  const oldStage=document.getElementById('photoStage'),scroller=document.querySelector('.main-workspace');
  if(oldStage&&scroller){
    const stage=oldStage.cloneNode(false);while(oldStage.firstChild)stage.appendChild(oldStage.firstChild);oldStage.replaceWith(stage);
    const photo=document.getElementById('wallPhoto');
    const insidePhoto=t=>{if(!photo||!photo.naturalWidth||!photo.naturalHeight)return false;const b=photo.getBoundingClientRect(),ia=photo.naturalWidth/photo.naturalHeight,ba=b.width/b.height;let w,h,l,top;if(ia>ba){w=b.width;h=w/ia;l=b.left;top=b.top+(b.height-h)/2}else{h=b.height;w=h*ia;top=b.top;l=b.left+(b.width-w)/2}return t.clientX>=l&&t.clientX<=l+w&&t.clientY>=top&&t.clientY<=top+h};
    let touch=null;stage.addEventListener('touchstart',e=>{if(e.touches.length!==1)return;const t=e.touches[0];touch={x:t.clientX,y:t.clientY,last:t.clientY,scroll:false,locked:insidePhoto(t)}},{capture:true,passive:true});
    stage.addEventListener('touchmove',e=>{if(!touch||e.touches.length!==1||touch.locked)return;const t=e.touches[0],dx=t.clientX-touch.x,dy=t.clientY-touch.y;if(!touch.scroll){if(Math.abs(dy)<12||Math.abs(dy)<=Math.abs(dx))return;touch.scroll=true}scroller.scrollTop-=t.clientY-touch.last;touch.last=t.clientY;e.preventDefault();e.stopImmediatePropagation()},{capture:true,passive:false});
    const end=()=>touch=null;stage.addEventListener('touchend',end,true);stage.addEventListener('touchcancel',end,true);
  }

  const drawing=document.getElementById('drawingCanvas'),panel=document.getElementById('productionMeasurementPanel'),widthHost=document.getElementById('measurementSequence'),heightHost=document.getElementById('heightMeasurementSequence');
  if(!(drawing&&panel&&widthHost&&heightHost))return;
  document.querySelector('.manual-dim-controls')?.remove();document.querySelector('.manual-dim-overlay')?.remove();document.querySelector('.pair-manual-controls')?.remove();document.querySelector('.pair-manual-overlay')?.remove();document.querySelector('.production-grid')?.classList.remove('manual-mode-hidden');
  widthHost.innerHTML='';heightHost.innerHTML='';localStorage.removeItem('splashcad-manual-stations-v1');

  const controls=document.createElement('div');controls.className='edge-manual-controls';
  controls.innerHTML='<div class="manual-dim-toggle"><button type="button" data-edge-mode="auto">Auto dimensions</button><button type="button" data-edge-mode="manual" class="active">Manual dimensions</button></div><div class="edge-manual-tools"><button type="button" data-edge-tool="width" class="active">1 · Touch width lines</button><button type="button" data-edge-tool="height">2 · Touch height lines</button><button type="button" data-edge-tool="enter">3 · Enter measurements</button><button type="button" data-edge-tool="delete">Delete last</button><button type="button" data-edge-tool="clear">Clear manual dims</button></div><div class="edge-manual-status">Widths: touch each actual drawing edge once. Blank space is ignored.</div>';
  panel.querySelector('.help')?.insertAdjacentElement('afterend',controls);
  const wrap=drawing.closest('.manual-dim-wrap')||drawing.parentElement;wrap.style.position='relative';const overlay=document.createElement('canvas');overlay.className='edge-manual-overlay';wrap.appendChild(overlay);
  let tool='width',widths=[],heights=[];const status=controls.querySelector('.edge-manual-status');
  const resize=()=>{const r=drawing.getBoundingClientRect(),d=window.devicePixelRatio||1;overlay.width=Math.max(1,Math.round(r.width*d));overlay.height=Math.max(1,Math.round(r.height*d));overlay.style.width=r.width+'px';overlay.style.height=r.height+'px';draw()};
  const toCanvas=e=>{const r=overlay.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*drawing.width,y:(e.clientY-r.top)/r.height*drawing.height}};
  const nearestEdge=p=>{const ctx=drawing.getContext('2d',{willReadFrequently:true}),rad=Math.max(8,Math.round(drawing.width/140)),x0=Math.round(p.x),y0=Math.round(p.y);let best=null,bestD=Infinity;try{const x=Math.max(0,x0-rad),y=Math.max(0,y0-rad),w=Math.min(drawing.width-x,rad*2+1),h=Math.min(drawing.height-y,rad*2+1),data=ctx.getImageData(x,y,w,h).data;for(let yy=0;yy<h;yy++)for(let xx=0;xx<w;xx++){const i=(yy*w+xx)*4,r=data[i],g=data[i+1],b=data[i+2],a=data[i+3];if(a<20)continue;const white=r>235&&g>235&&b>235;const red=r>145&&r>g*1.25&&r>b*1.2;const glassFill=r>160&&g>170&&b>175&&Math.max(r,g,b)-Math.min(r,g,b)<65;if(white||red||glassFill)continue;const px=x+xx,py=y+yy,d=Math.hypot(px-p.x,py-p.y);if(d<bestD){bestD=d;best={x:px/drawing.width,y:py/drawing.height}}}}catch{}return bestD<=rad?best:null};
  const bounds=()=>{const ctx=drawing.getContext('2d',{willReadFrequently:true}),w=drawing.width,h=drawing.height;let minX=w,maxX=0,minY=h,maxY=0,n=0;try{const data=ctx.getImageData(0,0,w,h).data,step=Math.max(3,Math.floor(w/400));for(let y=0;y<h;y+=step)for(let x=0;x<w;x+=step){const i=(y*w+x)*4,r=data[i],g=data[i+1],b=data[i+2];if(r>155&&g>165&&b>170&&r<240&&g<245&&b<250){minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y);n++}}}catch{}return n>20?{l:minX/w,r:maxX/w,t:minY/h,b:maxY/h}:{l:.16,r:.8,t:.18,b:.72}};
  const line=(c,x1,y1,x2,y2)=>{c.beginPath();c.moveTo(x1,y1);c.lineTo(x2,y2);c.stroke()};
  const draw=()=>{const c=overlay.getContext('2d'),d=window.devicePixelRatio||1;c.clearRect(0,0,overlay.width,overlay.height);const b=bounds(),L=b.l*overlay.width,R=b.r*overlay.width,T=b.t*overlay.height,B=b.b*overlay.height,dir=document.querySelector('input[name="measureDirection"]:checked')?.value||'ltr',datum=dir==='rtl'?R:L,red='#b91c1c',wit='#9ca3af';c.font='800 '+(12*d)+'px sans-serif';c.fillStyle=red;c.strokeStyle=red;c.lineWidth=1.5*d;
    widths.forEach((p,i)=>{const q={x:p.x*overlay.width,y:p.y*overlay.height},y=Math.max(18*d,T-(28+i*25)*d);c.strokeStyle=wit;c.setLineDash([4*d,4*d]);line(c,datum,T,datum,y);line(c,q.x,q.y,q.x,y);c.setLineDash([]);c.strokeStyle=red;line(c,datum,y,q.x,y);line(c,datum,y-5*d,datum,y+5*d);line(c,q.x,y-5*d,q.x,y+5*d);c.fillText('W'+(i+1),(datum+q.x)/2+5*d,y-7*d)});
    heights.forEach((p,i)=>{const q={x:p.x*overlay.width,y:p.y*overlay.height},nearLeft=Math.abs(q.x-L)<32*d,nearRight=Math.abs(q.x-R)<32*d;if(nearLeft||nearRight){const x=nearLeft?L-34*d:R+34*d;c.strokeStyle=red;c.setLineDash([]);line(c,x,B,x,q.y);line(c,x-5*d,B,x+5*d,B);line(c,x-5*d,q.y,x+5*d,q.y);c.fillText('H'+(i+1),x+(nearLeft?-30:10)*d,(B+q.y)/2)}else{const x=q.x,y=Math.min(overlay.height-20*d,B+(34+(i%3)*30)*d);c.strokeStyle=wit;c.setLineDash([4*d,4*d]);line(c,x,q.y,x,B);line(c,x,B,x,y-9*d);c.setLineDash([]);c.strokeStyle=red;line(c,x-5*d,q.y,x+5*d,q.y);line(c,x-5*d,B,x+5*d,B);c.fillText('H'+(i+1),x+8*d,y)}});
  };
  const update=()=>{status.textContent=tool==='width'?('Widths: '+widths.length+'. Touch each actual width edge once. Blank space is ignored.'):tool==='height'?('Heights: '+heights.length+'. Touch each actual height edge once. Witness lines are added automatically where needed.'):('Ready to enter '+widths.length+' widths first, then '+heights.length+' heights.')};
  const rows=()=>{widthHost.innerHTML=widths.map((p,i)=>'<div class="measure-sequence-row"><div class="measure-seq-no">'+(i+1)+'</div><div class="measure-seq-label">Width '+(i+1)+'</div><input class="measure-seq-input edge-measure-input" data-w="'+i+'" inputmode="decimal" placeholder="mm"></div>').join('');heightHost.innerHTML=heights.map((p,i)=>'<div class="measure-sequence-row"><div class="measure-seq-no">'+(i+1)+'</div><div class="measure-seq-label">Height '+(i+1)+'</div><input class="height-seq-input edge-measure-input" data-h="'+i+'" inputmode="decimal" placeholder="mm"></div>').join('');const inputs=[...panel.querySelectorAll('.edge-measure-input')];inputs.forEach((input,i)=>input.addEventListener('keydown',e=>{if(e.key!=='Enter')return;e.preventDefault();inputs[i+1]?.focus()||input.blur()}))};
  overlay.addEventListener('pointerdown',e=>{if(tool!=='width'&&tool!=='height')return;e.preventDefault();e.stopPropagation();const hit=nearestEdge(toCanvas(e));if(!hit){status.textContent='Touch an actual drawing line — blank space is ignored.';return}if(tool==='width')widths.push(hit);else heights.push(hit);draw();update()});
  controls.querySelectorAll('[data-edge-tool]').forEach(b=>b.addEventListener('click',()=>{const next=b.dataset.edgeTool;if(next==='delete'){if(tool==='height'&&heights.length)heights.pop();else if(tool==='width'&&widths.length)widths.pop();else if(heights.length)heights.pop();else widths.pop();draw();update();return}if(next==='clear'){widths=[];heights=[];widthHost.innerHTML='';heightHost.innerHTML='';draw();update();return}if(next==='enter'){tool='enter';controls.querySelectorAll('[data-edge-tool]').forEach(x=>x.classList.remove('active'));rows();update();panel.querySelector('.edge-measure-input')?.focus();return}tool=next;controls.querySelectorAll('[data-edge-tool]').forEach(x=>x.classList.toggle('active',x===b));draw();update()}));
  const alignDrawing=()=>{const card=drawing.closest('.drawing-card')||drawing.parentElement;if(scroller&&card){scroller.scrollTo({top:Math.max(0,card.offsetTop-6),behavior:'smooth'});setTimeout(resize,300)}};
  controls.querySelector('[data-edge-mode="manual"]').addEventListener('click',()=>setTimeout(alignDrawing,30));controls.querySelector('[data-edge-mode="auto"]').addEventListener('click',()=>location.reload());
  document.querySelectorAll('input[name="measureDirection"]').forEach(r=>r.addEventListener('change',draw));window.addEventListener('resize',resize);new ResizeObserver(resize).observe(drawing);setTimeout(()=>{resize();alignDrawing()},120);update();
})();
`;
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(CORE)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',event=>{
  if(event.request.method!=='GET'||new URL(event.request.url).pathname.startsWith('/api/'))return;
  const url=new URL(event.request.url);
  if(url.pathname==='/tablet.js'){
    event.respondWith(fetch(event.request).then(async response=>{const text=(await response.text()).replaceAll('UPDATE 006','UPDATE 014')+TABLET_PATCH;const fixed=new Response(text,{status:response.status,statusText:response.statusText,headers:{'Content-Type':'application/javascript; charset=utf-8','Cache-Control':'no-store'}});const copy=fixed.clone();caches.open(CACHE).then(cache=>cache.put(event.request,copy));return fixed;}).catch(()=>caches.match(event.request)));
    return;
  }
  event.respondWith(fetch(event.request).then(response=>{const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(event.request,copy));return response}).catch(()=>caches.match(event.request).then(hit=>hit||caches.match('/index.html'))));
});