const CACHE='splashcad-6-0-22-u028-durable-photo-import-20260817185000';
const CORE=['/','/index.html','/hob.html','/window.html','/styles.css','/splashcad-app.js','/window-wall.js','/voice.js','/tablet.js','/manifest.webmanifest','/splashcad-icon.svg'];
const TABLET_PATCH=`
;(()=>{
  const BUILD='ALPHA 6.0.22 · UPDATE 028';
  document.title='SplashCAD — '+BUILD;
  const proof=document.querySelector('.alpha-proof'); if(proof) proof.textContent=BUILD;
  const brand=document.querySelector('.brand p'); if(brand) brand.textContent=BUILD+' · Locked Detection + Dimension Engine V2';
  const style=document.createElement('style');
  style.textContent='body.tablet-field-mode .workspace-shell{grid-template-columns:155px minmax(0,1fr) 300px!important;gap:8px!important;height:calc(100vh - 64px)!important;overflow:hidden!important}body.tablet-field-mode .sidebar{display:block!important;grid-column:1!important;overflow:hidden!important}body.tablet-field-mode .sidebar>*:not(#tabletProcedurePanel){display:none!important}#tabletProcedurePanel{display:none}body.tablet-field-mode #tabletProcedurePanel{display:block!important;margin:0!important;position:sticky;top:0;padding:10px!important}#tabletProcedurePanel h2{margin:0 0 9px;font-size:13px;color:#d1fae5}#tabletProcedurePanel .procedure-step{padding:8px 0;border-top:1px solid #263a34;font-size:11px;line-height:1.3;color:#cbd5e1}#tabletProcedurePanel .procedure-step strong{display:block;color:#6ee7b7;font-size:12px;margin-bottom:2px}body.tablet-field-mode .main-workspace{grid-column:2!important;height:100%!important;min-height:0!important;overflow-y:auto!important;overflow-x:hidden!important;overscroll-behavior-y:contain!important;-webkit-overflow-scrolling:touch;padding-bottom:120px!important}body.tablet-field-mode .rightbar{grid-column:3!important;height:100%!important;max-height:none!important;min-height:0!important;overflow-y:auto!important;overscroll-behavior-y:contain!important;-webkit-overflow-scrolling:touch;padding-bottom:120px!important}body.tablet-field-mode #photoOverlay{touch-action:none!important}body.tablet-field-mode .photo-stage,body.tablet-field-mode #wallPhoto{min-height:68vh!important;max-height:82vh!important}';
  document.head.appendChild(style);
  const sidebar=document.querySelector('.sidebar');
  if(sidebar&&!document.getElementById('tabletProcedurePanel')){const panel=document.createElement('section');panel.id='tabletProcedurePanel';panel.className='panel';panel.innerHTML='<h2>Procedure</h2><div class="procedure-step"><strong>1 · Photo</strong>Take a photo or choose one.</div><div class="procedure-step"><strong>2 · Scan</strong>Scan outline + sockets.</div><div class="procedure-step"><strong>3 · Edit</strong>Correct outline, sockets, notches and shapes.</div><div class="procedure-step"><strong>4 · Measure</strong>Widths first, then heights.</div>';sidebar.prepend(panel);}
  document.querySelectorAll('.edge-manual-controls,.edge-manual-overlay,.manual-dim-controls,.manual-dim-overlay,.pair-manual-controls,.pair-manual-overlay,.height-layout-overlay,.witness-measure-overlay').forEach(el=>el.remove());
  document.querySelector('.production-grid')?.classList.remove('manual-mode-hidden');
  ['splashcad-manual-stations-v1','splashcad-manual-dimensions-v2','splashcad-manual-dimensions-v3','splashcad-manual-dimensions-v4'].forEach(k=>localStorage.removeItem(k));
  const overlay=document.getElementById('photoOverlay'),scroller=document.querySelector('.main-workspace');
  if(overlay&&scroller){let gesture=null;overlay.addEventListener('pointerdown',e=>{if(e.pointerType!=='touch')return;gesture={id:e.pointerId,startY:e.clientY,lastY:e.clientY,scrolling:false};},true);overlay.addEventListener('pointermove',e=>{if(!gesture||gesture.id!==e.pointerId||e.pointerType!=='touch')return;const total=e.clientY-gesture.startY,delta=e.clientY-gesture.lastY;if(!gesture.scrolling&&Math.abs(total)>10)gesture.scrolling=true;if(!gesture.scrolling)return;scroller.scrollTop-=delta;gesture.lastY=e.clientY;e.preventDefault();e.stopImmediatePropagation();},{capture:true,passive:false});const end=e=>{if(gesture&&gesture.id===e.pointerId)gesture=null;};overlay.addEventListener('pointerup',end,true);overlay.addEventListener('pointercancel',end,true);}
})();
`;
const patchSplashcadApp=(source)=>{
  source=source.replace(/const measurementNotchEntries = \(\) => \{[\s\S]*?\n  \};\n  const measurementNotches/,`const measurementNotchEntries = () => {\n    if(state.shoulderNotchesEnabled && (state.points||[]).length>=6){\n      const pts=state.points||[];\n      const xs=pts.map(p=>Number(p.x)).filter(Number.isFinite);\n      const manual=(state.notches||[]).filter(n=>!n?.shoulderAuto);\n      const oldAutos=(state.notches||[]).filter(n=>n?.shoulderAuto);\n      if(xs.length){\n        const spanX=Math.max(...xs)-Math.min(...xs);\n        const candidates=[];\n        for(let i=0;i<pts.length;i++){\n          const a=pts[i],b=pts[(i+1)%pts.length],prev=pts[(i-1+pts.length)%pts.length],next=pts[(i+2)%pts.length];\n          if(!a||!b||!prev||!next) continue;\n          const dx=Math.abs(Number(b.x)-Number(a.x)),dy=Math.abs(Number(b.y)-Number(a.y));\n          if(!(dx>spanX*0.06 && dy<=dx*0.12)) continue;\n          const leftVertical=Math.abs(Number(prev.x)-Number(a.x))<Math.max(10,Math.abs(Number(prev.y)-Number(a.y))*0.25);\n          const rightVertical=Math.abs(Number(next.x)-Number(b.x))<Math.max(10,Math.abs(Number(next.y)-Number(b.y))*0.25);\n          const prevLower=Number(prev.y)>Number(a.y)+8,nextLower=Number(next.y)>Number(b.y)+8;\n          const interior=Math.min(Number(a.x),Number(b.x))>Math.min(...xs)+spanX*0.05&&Math.max(Number(a.x),Number(b.x))<Math.max(...xs)-spanX*0.05;\n          if(leftVertical&&rightVertical&&prevLower&&nextLower&&interior){const left=Number(prev.x)<Number(next.x)?prev:next;const right=Number(prev.x)<Number(next.x)?next:prev;candidates.push({score:dx,left,right});}\n        }\n        candidates.sort((a,b)=>b.score-a.score);\n        const extractor=candidates[0];\n        if(extractor){\n          const nearestId=p=>{let best=null,bestD=Infinity;oldAutos.forEach(n=>{const d=Math.hypot(Number(n.x)-Number(p.x),Number(n.y)-Number(p.y));if(d<bestD){bestD=d;best=n;}});return best?._measureId;};\n          state.notches=[...manual,{x:extractor.left.x,y:extractor.left.y,shoulderAuto:true,_measureId:nearestId(extractor.left)},{x:extractor.right.x,y:extractor.right.y,shoulderAuto:true,_measureId:nearestId(extractor.right)}];\n        }\n      }\n    }\n    const entries=[];\n    (state.notches||[]).forEach((notch,index)=>{const x=Number(notch?.x),y=Number(notch?.y);if(!Number.isFinite(x)||!Number.isFinite(y))return;const duplicateIndex=entries.findIndex(item=>Math.abs(Number(item.notch.x)-x)<18&&Math.abs(Number(item.notch.y)-y)<18);if(duplicateIndex<0)entries.push({notch,index});else if(notch.shoulderAuto&&!entries[duplicateIndex].notch?.shoulderAuto)entries[duplicateIndex]={notch,index};});\n    return entries;\n  };\n  const measurementNotches`);
  source=source.replace(/const fittingFaceplateSize = \(socket\) => \{[\s\S]*?\n  \};/,`const fittingFaceplateSize = (socket) => {\n    const spec=cutoutSpec(socket);\n    if(socket?.type==="hole"){const diameter=Number(socket.editDiameter)>0?Number(socket.editDiameter):spec.width;return {width:diameter,height:diameter};}\n    const variable=["multiple","custom"].includes(socket?.type);\n    const edited=Boolean(socket?._sizeEdited);\n    return {width:(variable||edited)&&Number(socket.editWidth)>0?Number(socket.editWidth):spec.width,height:(variable||edited)&&Number(socket.editHeight)>0?Number(socket.editHeight):spec.height};\n  };`);
  source=source.replace('    state.sockets[i].editWidth = w;\n    state.sockets[i].editHeight = h;','    state.sockets[i].editWidth = w;\n    state.sockets[i].editHeight = h;\n    state.sockets[i]._sizeEdited = true;');
  source=source.replaceAll('const measuredW=Number(socket.editWidth)>0?Number(socket.editWidth):spec.width;','const measuredW=fittingFaceplateSize(socket).width;');
  source=source.replaceAll('const measuredH=Number(socket.editHeight)>0?Number(socket.editHeight):spec.height;','const measuredH=fittingFaceplateSize(socket).height;');
  source=source.replaceAll('const measuredW = Number(socket.editWidth) > 0 ? Number(socket.editWidth) : spec.width;','const measuredW = fittingFaceplateSize(socket).width;');
  source=source.replaceAll('const measuredH = Number(socket.editHeight) > 0 ? Number(socket.editHeight) : spec.height;','const measuredH = fittingFaceplateSize(socket).height;');

  // UPDATE 028: Android photo-picker references can lose permission after the
  // change event. Copy the selected file ONCE into app-owned bytes, then use
  // only that stable Blob/File for format checks, HEIC conversion and DataURL save.
  source=source.replace(
    '  const loadPhotoFile = async (file) => {\n    if (!file) return;\n    try {\n      const header = new Uint8Array(await file.slice(0, 16).arrayBuffer());',
    '  const loadPhotoFile = async (file) => {\n    if (!file) return;\n    try {\n      const ownedBytes = await file.arrayBuffer();\n      const ownedFile = new File([ownedBytes], file.name || "splashcad-photo", { type: file.type || "application/octet-stream", lastModified: Date.now() });\n      const header = new Uint8Array(ownedBytes.slice(0, 16));'
  );
  source=source.replaceAll('fileToDataUrl(new Blob([file], { type: "image/jpeg" }))','fileToDataUrl(new Blob([ownedFile], { type: "image/jpeg" }))');
  source=source.replaceAll('fileToDataUrl(new Blob([file], { type: "image/png" }))','fileToDataUrl(new Blob([ownedFile], { type: "image/png" }))');
  source=source.replaceAll('fileToDataUrl(file)','fileToDataUrl(ownedFile)');
  source=source.replaceAll('isHeicFile(file)','isHeicFile(ownedFile)');
  source=source.replaceAll('blob: file','blob: ownedFile');
  source=source.replace(
    '  $("libraryInput").addEventListener("change", (event) => {\n    loadPhotoFile(event.target.files?.[0]);\n  });',
    '  $("libraryInput").addEventListener("change", (event) => {\n    const selected=event.target.files?.[0];\n    loadPhotoFile(selected).finally(()=>{ event.target.value=""; });\n  });'
  );
  source=source.replace(
    '  $("cameraInput").addEventListener("change", (event) => {\n    loadPhotoFile(event.target.files?.[0]);\n  });',
    '  $("cameraInput").addEventListener("change", (event) => {\n    const selected=event.target.files?.[0];\n    loadPhotoFile(selected).finally(()=>{ event.target.value=""; });\n  });'
  );
  return source;
};
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(CORE)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',event=>{if(event.request.method!=='GET'||new URL(event.request.url).pathname.startsWith('/api/'))return;const url=new URL(event.request.url);if(url.pathname==='/tablet.js'){event.respondWith(fetch(event.request).then(async response=>{const text=(await response.text()).replaceAll('UPDATE 006','UPDATE 028')+TABLET_PATCH;const fixed=new Response(text,{status:response.status,statusText:response.statusText,headers:{'Content-Type':'application/javascript; charset=utf-8','Cache-Control':'no-store'}});const copy=fixed.clone();caches.open(CACHE).then(cache=>cache.put(event.request,copy));return fixed;}).catch(()=>caches.match(event.request)));return;}if(url.pathname==='/splashcad-app.js'){event.respondWith(fetch(event.request).then(async response=>{const text=patchSplashcadApp(await response.text());const fixed=new Response(text,{status:response.status,statusText:response.statusText,headers:{'Content-Type':'application/javascript; charset=utf-8','Cache-Control':'no-store'}});const copy=fixed.clone();caches.open(CACHE).then(cache=>cache.put(event.request,copy));return fixed;}).catch(()=>caches.match(event.request)));return;}event.respondWith(fetch(event.request).then(response=>{const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(event.request,copy));return response;}).catch(()=>caches.match(event.request).then(hit=>hit||caches.match('/index.html'))));});
